### PR TITLE
feat: add create etcd cluster and weed cluster function

### PR DESCRIPTION
**Pull request by sjcsjc123**
### Describe what this PR does / why we need it
Provide an interface to create a distributed file system and implement cluster mounting of rootfs

### Does this pull request fix one issue?

NONE

### Describe how you did it

Adopting decentralized weed cluster deployment method

- create etcd cluster
- start weed master
- register weed master to etcd cluster
- when upload or download, get service from etcd cluster

### Describe how to verify it

At present, the testing has not been completed yet, and will be improved in the future.

### Special notes for reviews

There is still a lot of unfinished work for this PR, and I will improve it as soon as possible and provide a functional test report.

- Need to combine `ssh` to start the etcd node and the weed node
- Need to consider whether to start the etcd cluster or weed cluster through k8s
- There is currently an issue with the go dependency file. Please wait for local repairs before uploading the go mod file.

### CODE REVIEW

**Comment by starnop** [comment]
@sjcsjc123 Thanks for your great work, and cloud you please make the CI all passed before it can be reviewed.

**Comment by sjcsjc123** [comment]
> @sjcsjc123 Thanks for your great work, and cloud you please make the CI all passed before it can be reviewed.

I will fix it in a few days and improve the testing. I have some things to do in the past few days.

**Comment by starnop** [comment]
@sjcsjc123 please squash your commits firstly

And In addition, regarding the comment in the [PR](https://github.com/sealerio/sealer/pull/2303), you can refer to see if there are similar problems

image

**Comment by sjcsjc123** [comment]
> @sjcsjc123 please squash your commits firstly
> 
> And In addition, regarding the comment in the [PR](https://github.com/sealerio/sealer/pull/2303), you can refer to see if there are similar problems
> 
> image

I got it. I will try to squash them.

**Comment by sjcsjc123** [comment]
> I got it. I will try to squash them.

**Comment by maxwell-can-not-fly** [comment]
I suggest following items to be done before merge: 1. finish testing and provide test evidence on basic functions 2. integrate with NewImageMounter() method and provide a switch to enable it (use previous implementation by default, use new implantation if user tell us to) 3. squash all commits into one to maintain a clear commit history

**Comment by maxwell-can-not-fly** [comment]
Going into alpha branch to meet SoC requirements, please see comment for follow up actions to be merge to main branch and next release.

**Pull request merged**
