### PR TITLE
chore: add e2e coverage and run e2e when pull request

### PR DESCRIPTION
**Pull request by zhy76**
### Describe what this PR does / why we need it
add e2e coverage and run e2e when pull request : after pull request will trigger e2e and we can see unitest coverage and e2e-test coverage,like:
image

### CODE REVIEW

**Review by kakaZhou719 — APPROVED** [review]
LGTM, we will fix those image E2E test firstly.

**Comment by kakaZhou719** [comment]
@zhy76 ，could we run whole E2E test when release the code ? 😃

**Comment by zhy76** [comment]
> 

Yes, when we pull request or push to release* branch will trigger e2e test.

**Comment by kakaZhou719** [comment]
hello ,@zhy76 , pls update your code, E2E test lint is fixed.

**Comment by zhy76** [comment]
image
Both of these errors were caused by sealer login failure, which is OK on my own repo, because it needs to use github secret, maybe we need to merge it to make it effective.
image

**Review by kakaZhou719 — APPROVED** [review]
LGTM

**Pull request merged**
