### PR TITLE
upgrade IsIpv4 method

### PR DESCRIPTION
**Pull request by zsyaoo**
use golang net package api to upgrade IsIpv4 method.

### CODE REVIEW

**Comment by justadogistaken** [comment]
@zsyaoo Great! But do we have some tests for this function?

**Comment by zsyaoo** [comment]
> @zsyaoo Great! But do we have some tests for this function?

I think `system api` or `simple code` no more need to tests

**Comment by zsyaoo** [comment]
> @zsyaoo Ok, I checked there is iputils_test.go. Actually I'm not talking about testing `net.ParseIP`, it's about testing the upper function. And there it is. Thanks.

IsIpv4 function are not used , i think it will be delete

**Comment by zsyaoo** [comment]
IsIpv4 function are not used,we can use `k8s.io/utils/net` IsIPv4String() function

**Pull request closed without merging**
