### PR TITLE
bugfix: set wrong auth domain at sealer login

### LINKED ISSUE #1459: When i use sealer login a http registry, it fails
#### What happened:

image

#### What you expected to happen:

I want sealer can login a http registry, because a log of private registry is run in http mode rather than https.

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by kakaZhou719**
### Does this pull request fix one issue?

Fixes #1459 
### Describe how you did it

only keep url host at config file for authorization reused if user try login with full url string.

### CODE REVIEW

**Comment by allencloud** [comment]
For these bugfix, we all need to add a test case to cover it. Otherwise, when project becomes complex, we have no idea about if this would introduce another bug, or break other normal functionality.

**Comment by VinceCui** [comment]
LGTM

**Review by VinceCui — COMMENTED** [review]
LGTM

**Review by VinceCui — COMMENTED** [review]
LGTM

**Review by VinceCui — APPROVED** [review]

**Pull request merged**
