### PR TITLE
remove --all flag for rmi

### PR DESCRIPTION
**Pull request by tgfree7**
Signed-off-by: tgfree <tgfree7@gmail.com>

### Describe what this PR does / why we need it

Remove flag `--all` for rmi. #1711

### CODE REVIEW

**Review by allencloud — APPROVED** [review]

**Comment by justadogistaken** [comment]
Why we remove this flag？

**Comment by tgfree7** [comment]
> Why we remove this flag？

Had discussed with @allencloud in the #1711 , remove all images might be a risk.

**Comment by tgfree7** [comment]
> Why we remove this flag？

Had discussed with @allencloud in the #1711 , remove all images might be a risk.

**Comment by justadogistaken** [comment]
@tgfree7 
Sorry, I didn't find the related discussion, Could you help to point that out?

**Comment by tgfree7** [comment]
> @tgfree7 Sorry, I didn't find the related discussion, Could you help to point that out?
Thanks for your detailed explanation. I strongly object to the flag --all/-a. This flag is a disaster for sealer. You know every command may be executed casually. If someone executes sealer rmi -a carelessly, the world explodes. So we could not provide such an easy way. I learnt some from Docker, and docker does not the --all flag in docker rmi. https://docs.docker.com/engine/reference/commandline/rmi/#options . If someone needs to remove all images, please guide him to use complicated command like for name in sealer image; do sealer rmi $name; done
image

**Pull request merged**
