### PR TITLE
make the log file more comprehensive

### PR DESCRIPTION
**Pull request by bxy4543**
Standard input and standard error are also logged to the log file.

### CODE REVIEW

**Comment by allencloud** [comment]
@bxy4543 Actually I am wondering if we need replace the self-define log package logger with some well-known log packages, like logrus and so on. 

Since in sealer, log implementation may not be the core part, and we can definitely reuse other's great work on log. 

In the logging planning, actually we should have several big steps, like:
* choosing a perfect log package, currently the self-defined logger may contain several issue, like blocking the `go test ./...` which is described in https://github.com/sealerio/sealer/issues/1360
* better log readability to improve user experience. 

@sealerio/sealer-maintainers WDYT?

**Comment by VinceCui** [comment]
https://github.com/sirupsen/logrus/issues/156

**Comment by VinceCui** [comment]
When we use logrus now, log will write to stderr. However, alse write log to a file maybe better.

See :https://github.com/sirupsen/logrus/issues/156

**Comment by VinceCui** [comment]
@bxy4543 

```go

        cwd, err := os.Getwd()
	if err != nil {
		log.Fatalf("Failed to determine working directory: %s", err)
	}
        runID := time.Now().Format("run-2006-01-02-15-04-05")
	logLocation := filepath.Join(cwd, runID + ".log")
	logFile, err := os.OpenFile(logLocation, os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		log.Fatalf("Failed to open log file %s for output: %s", logLocation, err)
	}
	log.SetOutput(io.MultiWriter(os.Stderr, logFile))
	log.RegisterExitHandler(func() {
		if logFile == nil {
			return
		}
		logFile.Close()
	})
	log.WithFields(log.Fields{"at": "start", "log-location": logLocation}).Info()
        // perform actions
	log.Exit(0)
```

**Comment by VinceCui** [comment]
I suggest that when log to file, the level is set to debug, cause when someone need to see the log file, that means some error has occur, and at that time, The more detailed the log, the better.

Any update? I think also log to file is a very important and emergency feat.

**Comment by bxy4543** [comment]
> 

Yes, I agree. But I'm not quite sure how to set the level of STDOUT to INFO and the level to DEBUG in the log file.

**Comment by allencloud** [comment]
Conflict Happens. Please rebase this. @bxy4543

**Pull request closed without merging**
