### PR TITLE
delete commandline

### PR DESCRIPTION
**Pull request by Stevent-fei**
### Describe what this PR does / why we need it
These documents are outdated, and we have instructions for using them. We don't need these redundant documents.

### CODE REVIEW

**Comment by allencloud** [comment]
> we have instructions for using them

@Stevent-fei I still have not gotten your initial thought on why to remove all these docs. Please explain more?

**Comment by Stevent-fei** [comment]
> > we have instructions for using them
> 
> @Stevent-fei I still have not gotten your initial thought on why to remove all these docs. Please explain more?

I think users prefer the official documentation to understand sealer. Few users will pay attention to this usage documentation, and many functions in the documentation are no longer applicable to the current version, and even affect the user experience

**Comment by allencloud** [comment]
> I think users prefer the official documentation to understand sealer.

@Stevent-fei I do agree. While where does official website to get the generated docs?

**Comment by Stevent-fei** [comment]
> > I think users prefer the official documentation to understand sealer.
> 
> @Stevent-fei I do agree. While where does official website to get the generated docs?

@allencloud https://github.com/sealerio/sealer.cool/tree/main/src/docs

**Pull request closed without merging**
